name: Docker Login and Push

on:
  push:
    branches:
      - main  

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16.14
        uses: actions/setup-node@v1
        with:
          node-version: 16.14

      - name: Build and Push Docker Image
        run: |
          echo ${{ secrets.HARPOON_TOKEN }} | docker login -u atest --password-stdin registry.harpooncorp.com
          docker build --platform linux/amd64 -t registry.harpooncorp.com/atest/harpoondemofront:latest .
          docker push registry.harpooncorp.com/atest/harpoondemofront:latest