name: Docker Login and Push

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: docker login https://registry.harpooncorp.com -u atest -p ${{ secrets.HARPOON_TOKEN }}

      - name: Build Docker image
        run: docker build -t harpoondemofront .

      - name: Tag Docker image
        run: docker tag harpoondemofront:latest registry.harpooncorp.com/atest/harpoondemofront:latest

      - name: Push Docker image to Docker Hub
        run: docker push registry.harpooncorp.com/atest/harpoondemofront:latest